### ISSUE TITLE
Misuse of LoadersOptionPlugin

### ISSUE THREAD

**Issue by dweber019** [easy-webpack/config-env-production#11]
Dear maintainer

The usage of the LoadersOptionPlugin should be removed from the following line:
https://github.com/easy-webpack/config-env-production/blob/master/src/index.ts#L73

Reason: As soon as this easyWebpack plugin uses the LoaderOptionsPlugin no one else can use the LoaderOptionsPlugin anymore.

Example: If I have any other webpack plugin, which requires configuration (e.g. tslint,....) this way, it wont work anymore, as the LoaderOptionsPlugin has already been used by this plugin.

Best regards

**Comment by niieani** [comment]
Hi @dweber019. You are absolutely right, and I am aware of thr problem. I'll try to think of a solution, but you are welcome to file a PR.

**Comment by dweber019** [comment]
Closing this issue as PR #12 will fix when merged
