### ISSUE TITLE
Build fails when string interpolation contains < sign

### ISSUE THREAD

**Issue by stevies** [easy-webpack/config-env-production#4]
In aurelia, ES6 webpack, if you do:

```
<span>${1 < 2}</span> 
```

The production fails with error:  

```
WARNING in ./src/views/index.html
Module build failed: Error: Parse Error: <= 2}
```

Dev build works OK.  So does:

```
    <span textContent.bind="1 < 2"></span> 
```

**Comment by niieani** [comment]
Must be the either the html-loader or the Aurelia one complaining. I'll add this to my todo list.

**Comment by niieani** [comment]
I can't reproduce this. Can you make an example repo?

**Comment by stevies** [comment]
Steps to make this fail. 

Clone the webpack skeleton.

https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

Run npm install. 

Run a production build - `npm run-script build:prod`\- it should work OK.

Add: 

```
 <span>${1 < 2}</span>
```

to any view  html - eg app.html.

```
<template>
  <require from="./nav-bar.html"></require>

  <nav-bar router.bind="router"></nav-bar>

  <div class="page-host">
    <router-view></router-view>
  </div>

  <span>${1 < 2}</span>

</template>
```

Try to do a production build - `npm run-script build:prod`\- watch it fail.  Error is:

```
WARNING in ./src/app.html
Module build failed: Error: Parse Error: < 2}</span>
</template> 
    at new HTMLParser (/home/xxx/IdeaProjects/web/skeleton-navigation/skeleton-esnext-webpack/node_modules/html-minifier/src/htmlparser.js:236:13)
    at minify (/home/xxx/IdeaProjects/web/skeleton-navigation/skeleton-esnext-webpack/node_modules/html-minifier/src/htmlminifier.js:954:3)
    at Object.exports.minify (/home/xxx/IdeaProjects/web/skeleton-navigation/skeleton-esnext-webpack/node_modules/html-minifier/src/htmlminifier.js:1307:10)
    at Object.module.exports (/home/xxx/IdeaProjects/web/skeleton-navigation/skeleton-esnext-webpack/node_modules/html-loader/index.js:119:26)
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

I'll put something online later if it helps. No rush on this one - it's not causing me any problems right now - easy to work around.

**Comment by nkoterba** [comment]
@niieani I'm facing a similar issue with another library. But I believe it's the html-loader's internal use of html-minifer when using the html-loader option of `minimize=true`.

Next step is to see if html-minifer provides a way to handle boolean logic in inline templates.

**Comment by niieani** [comment]
Yes, you're right. The problem is with `html-minifier`. If any of you find a solution to handle this, please make a PR.
